import { Lexend_Deca } from 'next/font/google'
import './globals.css'

const lexend_deca = Lexend_Deca({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={lexend_deca.className}>{children}</body>
    </html>
  )
}
